import { createRoutine } from 'redux-saga-routines';


const CREATE_CHAT_MESSAGE = createRoutine('CREATE_CHAT_MESSAGE');
const CREATE_INTERLOCUTOR_MESSAGE = createRoutine('CREATE_INTERLOCUTOR_MESSAGE');

const GET_ALL_CHATS = createRoutine('GET_ALL_CHATS');
const GET_CHAT_GROUP = createRoutine('GET_CHAT_GROUP');
const CREATE_CHAT_GROUP = createRoutine('CREATE_CHAT_GROUP');
const GET_ALL_CONTACTS = createRoutine('GET_ALL_CONTACTS');
const ADD_MEMBER_GROUP = createRoutine('ADD_MEMBER_GROUP');
const DELETE_MEMBER_GROUP = createRoutine('DELETE_MEMBER_GROUP');
const DELETE_GROUP = createRoutine('DELETE_GROUP');
const GET_ALL_MESSAGES = createRoutine('GET_ALL_MESSAGES');
const GET_MESSAGES_BY_CHAT = createRoutine('GET_MESSAGES_BY_CHAT');
const CHANGE_CHAT_GROUP_TITLE = createRoutine('CHANGE_CHAT_GROUP_TITLE');
const CREATE_PRIVATE_CHAT = createRoutine('CREATE_PRIVATE_CHAT');
const GET_PRIVATE_CHAT = createRoutine('GET_PRIVATE_CHAT');
const DELETE_INTERLOCUTOR_CHAT = createRoutine('DELETE_INTERLOCUTOR_CHAT');
const GET_INTERLOCUTOR_MESSAGES = createRoutine('GET_INTERLOCUTOR_MESSAGES');
const GET_INTERLOCUTOR_CHAT = createRoutine('GET_INTERLOCUTOR_CHAT');

export default {
	GET_ALL_CHATS,
	GET_CHAT_GROUP,
	CREATE_CHAT_GROUP,
	GET_ALL_CONTACTS,
	ADD_MEMBER_GROUP,
	DELETE_MEMBER_GROUP,
	CREATE_CHAT_MESSAGE,
	DELETE_GROUP,
	GET_ALL_MESSAGES,
	GET_MESSAGES_BY_CHAT,
	CHANGE_CHAT_GROUP_TITLE,
	CREATE_PRIVATE_CHAT,
	GET_PRIVATE_CHAT,
	DELETE_INTERLOCUTOR_CHAT,
	CREATE_INTERLOCUTOR_MESSAGE,
	GET_INTERLOCUTOR_MESSAGES,
	GET_INTERLOCUTOR_CHAT,
};
