export const DEFAULT_PREFIX = 'REDUX_WEBSOCKET::';

// Library dispatched action types.
export const WEBSOCKET_BEGIN_RECONNECT = DEFAULT_PREFIX + 'BEGIN_RECONNECT';
export const WEBSOCKET_RECONNECT_ATTEMPT = DEFAULT_PREFIX + 'RECONNECT_ATTEMPT';
export const WEBSOCKET_RECONNECTED = DEFAULT_PREFIX + 'RECONNECTED';
export const WEBSOCKET_BROKEN = DEFAULT_PREFIX + 'BROKEN';
export const WEBSOCKET_CLOSED = DEFAULT_PREFIX + 'CLOSED';
export const WEBSOCKET_ERROR = DEFAULT_PREFIX + 'ERROR';
export const WEBSOCKET_MESSAGE = DEFAULT_PREFIX + 'MESSAGE';
export const WEBSOCKET_OPEN = DEFAULT_PREFIX + 'OPEN';

// User dispatched action types.
export const WEBSOCKET_CONNECT = DEFAULT_PREFIX + 'CONNECT';
export const WEBSOCKET_DISCONNECT = DEFAULT_PREFIX + 'DISCONNECT';
export const WEBSOCKET_SEND = DEFAULT_PREFIX + 'SEND';
