import { createRoutine } from 'redux-saga-routines';
const GET_COLLECTOR_MIGRATE_CALENDAR = createRoutine('GET_COLLECTOR_MIGRATE_CALENDAR');
const GET_COLLECTOR_DASHBOARD_ONE = createRoutine('GET_COLLECTOR_DASHBOARD_ONE');
const GET_COLLECTOR_DASHBOARD_THREE = createRoutine('GET_COLLECTOR_DASHBOARD_THREE');
const GET_COLLECTOR_DASHBOARD_CHART_LIST = createRoutine('GET_COLLECTOR_DASHBOARD_CHART_LIST');
const GET_COLLECTOR_CONTROLLER_VIEW_USER_INFO = createRoutine('GET_COLLECTOR_CONTROLLER_VIEW_USER_INFO');
const SEND_EMPLOYEES_IDS_IMPORT = createRoutine('SEND_EMPLOYEES_IDS_IMPORT');
const CHOOSED_EMPLOYEES_DROPDOWN = createRoutine('CHOOSED_EMPLOYEES_DROPDOWN');
const SEND_USERID_AND_EMPLOYEES_IDS = createRoutine('SEND_USERID_AND_EMPLOYEES_IDS');
const GET_BONUS_LIST = createRoutine('GET_BONUS_LIST');
const GET_BONUS_CHART = createRoutine('GET_BONUS_CHART');
const GET_BONUS_DETAIL_PAY = createRoutine('GET_BONUS_DETAIL_PAY');
const GET_BONUS_USER = createRoutine('GET_BONUS_USER');
const GET_EMPLOYEES_LIST = createRoutine('GET_EMPLOYEES_LIST');
const GET_SAVED_STATUS_COMMENT = createRoutine('GET_SAVED_STATUS_COMMENT');
const CHANGE_CATEGORY = createRoutine('CHANGE_CATEGORY');
const CHANGE_CATEGORY_MONITORING = createRoutine('CHANGE_CATEGORY_MONITORING');
export default {
	GET_COLLECTOR_MIGRATE_CALENDAR,
	GET_COLLECTOR_DASHBOARD_ONE,
	GET_COLLECTOR_DASHBOARD_THREE,
	GET_COLLECTOR_DASHBOARD_CHART_LIST,
	GET_COLLECTOR_CONTROLLER_VIEW_USER_INFO,
	SEND_EMPLOYEES_IDS_IMPORT,
	CHOOSED_EMPLOYEES_DROPDOWN,
	SEND_USERID_AND_EMPLOYEES_IDS,
	GET_BONUS_LIST,
	GET_BONUS_CHART,
	GET_BONUS_DETAIL_PAY,
	GET_BONUS_USER,
	GET_EMPLOYEES_LIST,
	GET_SAVED_STATUS_COMMENT,
	CHANGE_CATEGORY,
	CHANGE_CATEGORY_MONITORING
};
