const config = {
  APPNAME: "APP",
  ROUTE_BASENAME: "",
  //API_ROOT: window.location.origin + ':99/v1',
  DEFAULT_LANG_CODE: "ru",
  PROJECT_ID: "bhm_one",
  // API_ROOT: 'http://localhost:60/v1',
  API_ROOT: "http://172.28.6.124:99/v1",
  WEB_SOCKET_URL: "ws://172.28.6.124:9502",
  ROLES: {
    DEPARTMENT_MANAGER: "department_manager",
    FACE_CONTROL_ADMIN: "face_control_admin",
    COLLECTOR_ADMIN: "collector_admin",
    COLLECTOR_FILIAL: "collector_filial",
    COLLECTOR_FILIAL_MANAGER: "collector_filial_manager",
    COLLECTOR_REGION_MANAGER: "collector_region_manager",
    COLLECTOR_CREDIT_ASSIGNER: "collector_credit_assigner",
    RESPUBLIC: "republic",
    VACANCY_HR_MANAGER: "vacancy_hr_role",
    VACANCY_DEPARTMENT_MANAGER: "vacancy_department_manager",
    VACANCY_FILIAL_MANAGER: "vacancy_filial_manager",
    STREAM_ADMIN: "stream_admin",
    STREAM_TAB_ADMIN: "stream_tab_admin",
    BONUS: "bonus",
    CURRENCY: "currency",
    COURSE: "course",
    MONITORING_ADMIN: "monitoring_admin",
    MONITORING_REPUBLIC: "monitoring_republic",
    MONITORING_FILIAL: "monitoring_filial",
    MONITORING_REGION: "monitoring_region",
    LANGUAGE_ADMIN: "language_admin",
    SMS_ADMIN: "sms_admin",
    APPEAL: "appeal",
    MONITORING_PROBLEM_REPUBLIC: "monitoring_problem_republic",
    MONITORING_PROBLEM_REGION: "monitoring_problem_region",
    MONITORING_PROBLEM_FILIAL: "monitoring_problem_filial",
    MONITORING_PROBLEM_ADMIN: "monitoring_problem_admin",
    MONITORING_TREASURY: "monitoring_treasury",
    MONITORING_OPERATION: "monitoring_operation",
    USER: "user",
    BONUS_FILIAL_REGISTRAR:"bonus_filial_registrar"
  },
  STYLE: {
    danger: "red",
    warning: "gold",
    info: "cyan",
    success: "green",
    primary: "blue",
    dark: "default",
    null: "blue",
  },
};

export default config;
